version: '2'

services:
  auctioneer-ca:
    container_name: auctioneer-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: auctioneer-ca
    ports:
    - 7054:7054

  member-ca:
    container_name: member-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: member-ca
    ports:
    - 8054:7054

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050

  auctioneer-peer:
    container_name: auctioneer-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: auctioneer-peer
    environment:
    - CORE_PEER_ID=auctioneer-peer
    - CORE_PEER_ADDRESS=auctioneer-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=auctioneer-peer:7051
    - CORE_PEER_LOCALMSPID=auctioneerOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0

  member-peer:
    container_name: member-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: member-peer
    environment:
    - CORE_PEER_ID=member-peer
    - CORE_PEER_ADDRESS=member-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=member-peer:7051
    - CORE_PEER_LOCALMSPID=memberOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - auctioneer-peer

