version: "3"
services:
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit1
    volumes:
      - "./RabbitMQ/rabbitmq.config:/etc/RabbitMQ/rabbitmq.config"
      - "./RabbitMQ/definitions.json:/etc/RabbitMQ/definitions.json"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    networks:
      - rabbitmq-cluster

  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    volumes:
      - "./RabbitMQ/rabbitmq.config:/etc/RabbitMQ/rabbitmq.config"
      - "./RabbitMQ/definitions.json:/etc/RabbitMQ/definitions.json"
    networks:
      - rabbitmq-cluster

  rabbit3:
    image: rabbitmq:3-management
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit3
    volumes:
      - "./RabbitMQ/rabbitmq.config:/etc/RabbitMQ/rabbitmq.config"
      - "./RabbitMQ/definitions.json:/etc/RabbitMQ/definitions.json"
    networks:
      - rabbitmq-cluster
  redis1:
    image: redis:3
    ports:
      - "7000:7000"
    volumes:
      - ./Redis/redis-cluster1.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
  redis2:
    image: redis:3
    ports:
      - "7001:7001"
    volumes:
      - ./Redis/redis-cluster2.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
  redis3:
    image: redis:3
    ports:
      - "7002:7002"
    volumes:
      - ./Redis/redis-cluster3.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
  redis-cluster:
    tty: true
    build:
      context: ./Redis
      args:
        redis_version: '3.2.9'
    hostname: server
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - redis-cluster

networks:
  rabbitmq-cluster:
  redis-cluster: